version: "2"
services:
  
  python:
    container_name: python
    build: 
      context: .
      dockerfile: app/app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file: 
      - ./.env
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local